apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: production-main-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: cafekec.shop
    http:
      paths:
      - path: /main(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: web-v2-service
            port:
              number: 80
      - path: /api/main/weather(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: kma-api
            port:
              number: 8080
      - path: /api/main/energy(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: energy-api
            port:
              number: 8000
      - path: /health/global-status(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: energy-api
            port:
              number: 8000
      - path: /api/ai(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ai-rag
            port:
              number: 3000