apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

# 일반 리소스
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

# 이름 뒤에 해시값(랜덤 문자) 붙는 것 방지
generatorOptions:
  disableNameSuffixHash: true