apiVersion: v1
kind: Service
metadata:
  name: web-v2-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: web-v2-dashboard
  ports:
  - name: web
    port: 80
    targetPort: 80

